services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-pos-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: restaurant-pos-db
    environment:
      POSTGRES_DB: restaurant_pos
      POSTGRES_USER: danielxxomg
      POSTGRES_PASSWORD: 4033
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: restaurant-pos-adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: restaurant-pos-ngrok
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      ['http', '--domain', 'surely-harmless-colt.ngrok-free.app', 'app:3000']
    ports:
      - '4040:4040'

volumes:
  postgres_data:
