services:
  db:
    image: postgres:15
    container_name: restaurant-pos-db
    environment:
      POSTGRES_DB: restaurant_pos
      POSTGRES_USER: danielxxomg
      POSTGRES_PASSWORD: 4033
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: restaurant-pos-adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: restaurant-pos-ngrok
    environment:
      NGROK_AUTHTOKEN: 2muY3XTARIEsu7geItCddnchrqk_2Ld6F3VafZh1cs1kgGkz7
    command: http --domain=surely-harmless-colt.ngrok-free.app 3000
    ports:
      - '4040:4040'
    depends_on:
      - db
      - adminer
    restart: unless-stopped

volumes:
  postgres_data:
